version: '3.9'
services:                     
  mongodb:
    image: mongo:5.0
    container_name: cosc404-lab07-mongodb
    ports:
    - 27017:27017
    volumes:
    - mongodb:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=lab7
    - MONGO_INITDB_ROOT_PASSWORD=404mgbpw
  # node api
  api:
    build: .
    ports:
    - 3000:3000
    depends_on: 
    - mongodb

volumes:     
    mongodb:   